export const AGREGAR_GUARDA = "AGREGAR_GUARDA";
export const AGREGAR_GUARDA_EXITO = "AGREGAR_GUARDA_EXITO";
export const AGREGAR_GUARDA_ERROR = "AGREGAR_GUARDA_ERROR";


export const AGREGAR_DOTACION = "AGREGAR_DOTACION";
export const AGREGAR_DOTACION_EXITO = "AGREGAR_DOTACION_EXITO";
export const AGREGAR_DOTACION_ERROR = "AGREGAR_DOTACION_ERROR";

