export const AGREGAR_GUARDA = "AGREGAR_GUARDA";
export const AGREGAR_GUARDA_EXITO = "AGREGAR_GUARDA_EXITO";
export const AGREGAR_GUARDA_ERROR = "AGREGAR_GUARDA_ERROR";

export const COMENZAR_DESCARGA_GUARDA = "COMENZAR_DESCARGA_GUARDA";
export const DESCARGA_GUARDA_EXITO = "DESCARGA_GUARDA_EXITO";
export const DESCARGA_GUARDA_ERROR = "DESCARGA_GUARDA_ERROR";

export const OBTENER_GUARDA_ELIMINAR = "OBTENER_GUARDA_ELIMINAR";
export const GUARDA_ELIMINADO_EXITO = "GUARDA_ELIMINADO_EXITO";
export const GUARDA_ELIMINADO_ERROR = "GUARDA_ELIMINADO_ERROR";

export const OBTENER_GUARDA_EDITAR = "OBTENER_GUARDA_EDITAR";
export const COMENZAR_EDICION_GUARDA = "COMENZAR_EDICION_GUARDA";
export const GUARDA_EDITADO_EXITO = "GUARDA_EDITADO_EXITO";
export const GUARDA_EDITADO_ERROR = "GUARDA_EDITADO_ERROR";




export const AGREGAR_DOTACION = "AGREGAR_DOTACION";
export const AGREGAR_DOTACION_EXITO = "AGREGAR_DOTACION_EXITO";
export const AGREGAR_DOTACION_ERROR = "AGREGAR_DOTACION_ERROR";

export const COMENZAR_DESCARGA_DOTACION = "COMENZAR_DESCARGA_DOTACION";
export const DESCARGAR_DOTACION_EXITO = "DESCARGAR_DOTACION_EXITO";
export const DESCARGAR_DOTACION_ERROR = "DESCARGAR_DOTACION_ERROR";

export const OBTENER_DOTACION_ELIMINAR = "OBTENER_DOTACION_ELIMINAR";
export const DOTACION_ELIMINADO_EXITO = "DOTACION_ELIMINADO_EXITO";
export const DOTACION_ELIMINADO_ERROR = "DOTACION_ELIMINADO_ERROR";

export const OBTENER_DOTACION_EDITAR = "OBTENER_DOTACION_EDITAR";
export const COMENZAR_EDICION_DOTACION = "COMENZAR_EDICION_DOTACION";
export const DOTACION_EDITADO_EXITO = "DOTACION_EDITADO_EXITO";
export const DOTACION_EDITADO_ERROR = "DOTACION_EDITADO_ERROR";




export const MOSTRAR_ALERTA= 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA= 'OCULTAR_ALERTA';



