export const AGREGAR_GUARDA = "AGREGAR_GUARDA";
export const AGREGAR_GUARDA_EXITO = "AGREGAR_GUARDA_EXITO";
export const AGREGAR_GUARDA_ERROR = "AGREGAR_GUARDA_ERROR";

export const COMENZAR_DESCARGA_GUARDA = "COMENZAR_DESCARGA_GUARDA";
export const DESCARGA_GUARDA_EXITO = "DESCARGA_GUARDA_EXITO";
export const DESCARGA_GUARDA_ERROR = "DESCARGA_GUARDA_ERROR";



export const AGREGAR_DOTACION = "AGREGAR_DOTACION";
export const AGREGAR_DOTACION_EXITO = "AGREGAR_DOTACION_EXITO";
export const AGREGAR_DOTACION_ERROR = "AGREGAR_DOTACION_ERROR";

export const COMENZAR_DESCARGA_DOTACION = "COMENZAR_DESCARGA_DOTACION";
export const DESCARGAR_DOTACION_EXITO = "DESCARGAR_DOTACION_EXITO";
export const DESCARGAR_DOTACION_ERROR = "DESCARGAR_DOTACION_ERROR";
